### ISSUE TITLE
描述未超過500個字，仍會跳出錯誤

### ISSUE THREAD

**Issue by yaochangyu** [demofan/dotblogs#14]
測試資料：
續上篇：http://www.dotblogs.com.tw/yc421206/archive/2015/10/12/153536.aspx

有關 Elmah 的設定請參考：http://www.dotblogs.com.tw/yc421206/archive/2014/05/22/145209.aspx

Nuget 上有一套 NLog.Elmah 的套件，顧名思義這是用來整合 Elmah 的套件，NLog 不像 Elmah 那樣有漂亮的報表可以看，藉由這個套件可以輕鬆讓 NLog 整合至 Elmah，簡單來講就是在 NLog 的 target 增加一個 Elmah

結果：
請勿輸入超過 500 個字

**Comment by demofan** [comment]
我將以上的字全部貼上後並無跳出「請勿輸入超過 500 個字」建議您切換到「原始碼」狀態看看是不是有過多無意義的 Html Tag

**Comment by yaochangyu** [comment]
果然有
我是文章本體copy到描述，所以不能直接這樣copy?

**Comment by demofan** [comment]
你可以這樣貼但要注意包含HTML不能超過500字，如果要貼純文字可利用編輯器的貼上功能
