### ISSUE TITLE
大量處理文章及標籤分類，操作起來速度不夠流暢，每次存檔，都會回到第一頁

### ISSUE THREAD

**Issue by yaochangyu** [demofan/dotblogs#16]
scenario
Given I stay Page Index =2
When I press save button
Then Page Index=0

**Comment by demofan** [comment]
如果你修改了內容依然停在第二頁，那時候的第二頁就和原本的第二頁就不一樣了。

**Comment by yaochangyu** [comment]
我改第二頁或其他頁面的內容，內容變了，Page Index可以不用變阿，還是你是說order的順序也變了?弱是就找一個不會變的欄位來排序
還是有其他方法可以大量編輯分類?
