### ISSUE TITLE
透過CKEditor編輯文章時，文章的游標無法透過滑鼠指定游標位置

### ISSUE THREAD

**Issue by d8958101** [demofan/dotblogs#17]
在ckeditor裡面編輯文章時，原本的習慣是有時候會用鍵盤的方向鍵去移動游標，有時候會用滑鼠去移動游標，然後再去打字。但是現在只能用鍵盤方向鍵去移動，一旦用滑鼠在CKEDITOR的編輯文字區裡面任何一個位置點了一下，游標就會看不見，然後就不知道你接下來打的字會出現在哪個位置

**Comment by demofan** [comment]
請問你的作業系統與瀏覽器版本

**Comment by d8958101** [comment]
感謝回應，我的作業系統是win 8 , 瀏覽器是chrome 46.0

**Comment by demofan** [comment]
已經修復
