### ISSUE TITLE
能否首頁熱門文章/最新文章 顯示作者名稱與連結

### ISSUE THREAD

**Issue by dotjum** [demofan/dotblogs#23]
如下圖紅框處，可以知道哪個作者名稱與可以點選到他的部落格

![image](https://cloud.githubusercontent.com/assets/5997139/11387636/86813f04-9367-11e5-8779-d3e6b35381fc.png)

**Comment by demofan** [comment]
這是故意設計的，我們希望瀏覽者是因為文章內容而點進去，不是因為作者是誰而點進去

**Comment by SuperShowwei** [comment]
我支這個設計。

**Comment by demofan** [comment]
對了，補充一下「熱門文章」目前是人工選的所以品質會有一定的保證
在我還沒想到可行的演算法之前都會是人工處理

**Comment by SuperShowwei** [comment]
這幾天來的疑問終於解開了。

**Comment by dotjum** [comment]
我其實不會依照是誰的文章去看，我表達的是 文章是誰發表的文章，標註它的名稱，對於作者來說，是一個顯示出來這篇文章是這個作者的，而不是站方自己的文章。

**Comment by demofan** [comment]
已增加標示
