### ISSUE TITLE
這兩天發現的問題列表

### ISSUE THREAD

**Issue by mis2000lab** [demofan/dotblogs#25]
您好：

因為我的文章數量較多，關於這幾天發現的問題：
1. 有些文章消失了，例如 http://www.dotblogs.com.tw/mis2000lab/archive/2014/08/29/ado.net_parameter_sql_injection_20140829.aspx
   但進入後台管理區，發現此文還在，我重新存檔一次，還是看不見。
    文章數量較多，我還在找哪些文章遺失

2. 舊文章無法修改，源自「檔名」裡面我用了 - 符號而非底線
   新文章會警告不得使用，但舊文章卻連修改內容都禁止了（無法存檔）

3. 關鍵字消失
   假設我的文章有設定一個關鍵字，名為「參數」
   當初可以用這樣的URL，列出這個關鍵字的所有文章 
   例如 www.dotblogs.com.tw/mis2000lab/Tags/參數/default.aspx
   我的範例多，所以大量使用這樣的超連結，
   我透過google搜尋自己舊文章也是這樣找，但現在都失效了。

4. 點選我的Blog上方的「標題」，能否連回自己的首頁？
   舉例來說，我在第四頁 www.dotblogs.com.tw/mis2000lab/4
   點選上方「Blog標題」，還停留在同一頁，無法回到首頁（第一頁）。

5. 文章分類（您說的系列文章）遇見「空白」或是「/」符號就失效
   我有一個文章分類名為「ADO.NET / LINQ / SQL / Entity」
   無法列出這分類的所有文章，出現錯誤訊息
   https://www.dotblogs.com.tw/mis2000lab/series/ado.net%20/%20linq%20/%20sql%20/%20entity/1

以下是建議的功能，應該說是舊的功能希望能恢復

1. 只要我登入成功以後，希望我的首頁，每篇文章前面出現「修改」符號（例如一支筆的icoin）
   因為文章太多，以前可以即時修改，很方便。
   現在要進入管理區，搜尋「關鍵字」才能改，步驟很多。

2. 側邊才能出現網路廣告，目前 BloggerAds這家國內廠商的廣告，無法呈現      
<script type="text/javascript" src="http://js1.bloggerads.net/showads.aspx?blogid=20080619000054&amp;charset=utf-8"></script>

謝謝各位，辛苦了  :-)

**Comment by mis2000lab** [comment]
補充說明　-- 側邊才能出現網路廣告，目前 BloggerAds這家國內廠商的廣告，無法呈現 
他們採用的是 "script標籤" 來做廣告
我有PO一個範例，但被系統過濾掉了

**script type="text/javascript" src="http://js1.bloggerads.net/showads.aspx?blogid=1234567&amp;charset=utf-8" **
**/script**

**Comment by demofan** [comment]
建議下次回報問題時可以逐項回報，不然這樣的列表其實滿難回覆的 ^.^

您好：

因為我的文章數量較多，關於這幾天發現的問題：
 1. 有些文章消失了，例如 http://www.dotblogs.com.tw/mis2000lab/archive/2014/08/29/ado.net_parameter_sql_injection_20140829.aspx
 但進入後台管理區，發現此文還在，我重新存檔一次，還是看不見。
 文章數量較多，我還在找哪些文章遺失

> 非常抱歉！因為原本連結中包含 . 新版因為效能考量已經忍痛捨去對於 . 的解析，您也同樣是寫.net 的應該可以體諒

1.舊文章無法修改，源自「檔名」裡面我用了 - 符號而非底線
 新文章會警告不得使用，但舊文章卻連修改內容都禁止了（無法存檔）

> 這點在您回報前就已經調整了，因為您一起回報，所以無法提早回覆您

2.關鍵字消失
 假設我的文章有設定一個關鍵字，名為「參數」
 當初可以用這樣的URL，列出這個關鍵字的所有文章 
 例如 www.dotblogs.com.tw/mis2000lab/Tags/參數/default.aspx
 我的範例多，所以大量使用這樣的超連結，
 我透過google搜尋自己舊文章也是這樣找，但現在都失效了。

> 已增加舊網址對應

3.點選我的Blog上方的「標題」，能否連回自己的首頁？
 舉例來說，我在第四頁 www.dotblogs.com.tw/mis2000lab/4
 點選上方「Blog標題」，還停留在同一頁，無法回到首頁（第一頁）。

> 已強制回到第一頁

4.文章分類（您說的系列文章）遇見「空白」或是「/」符號就失效
 我有一個文章分類名為「ADO.NET / LINQ / SQL / Entity」
 無法列出這分類的所有文章，出現錯誤訊息
https://www.dotblogs.com.tw/mis2000lab/series/ado.net%20/%20linq%20/%20sql%20/%20entity/1

> 這部分也是要忍痛放棄的部分，因為這牽扯到了 IIS 的生命週期，可能要請您多包涵了

以下是建議的功能，應該說是舊的功能希望能恢復

1.只要我登入成功以後，希望我的首頁，每篇文章前面出現「修改」符號（例如一支筆的icoin）
 因為文章太多，以前可以即時修改，很方便。
 現在要進入管理區，搜尋「關鍵字」才能改，步驟很多。

> 已增加連結


2.側邊才能出現網路廣告，目前 BloggerAds這家國內廠商的廣告，無法呈現 

> 這是因為 BloggerAds 這家部落格公司的 javascript 不支援 Https 安全連線導致，我已經去電該公司詢問，他們說最快也要明年才有可能調整（而且回答的很心虛）或許您可以考慮換一家的廣告放


謝謝各位，辛苦了 :-)
