### ISSUE TITLE
意外的草稿 ??

### ISSUE THREAD

**Issue by mis2000lab** [demofan/dotblogs#26]
您好：

這兩天修改舊文章時，不知道觸動了什麼？
一直出現「意外的草稿 --請注意只要您存檔過任何一篇文章，意外的草稿就會全部移除！」
而無法存檔

我也不知道這是什麼意思，或應該如何避免、排除？

一直卡住，無法PO文章，也無法修改舊的文章。
有地方給我刪除這些「意外的草稿」嗎？

Thanks :-)

**Comment by demofan** [comment]
我想釐清
「一直卡住，無法PO文章，也無法修改舊的文章。」
是哪裡卡住？

**Comment by mis2000lab** [comment]
您好：

1. 我修改一篇*舊*文章之後，按下「儲存」
然後就出現警告訊息
怎麼按下按鈕都無法存檔。

我只好登出，重新登入，重新修改這篇*舊*文章
然後按下儲存又OK了。

我不清楚這功能是怎麼出來的？我怎麼觸發他？
他好心幫我存了草稿，我可以刪除這些草稿嗎？
這些草稿讓我無法存檔，就卡住了

2. 昨天上午，我發一篇*新*文章（不是改舊文章）
按下儲存，又出來了，又卡住了。
這次更誇張，有兩篇一模一樣的草稿出現，卡住我，不給我PO文

很困擾。

不好意思，要請您幫幫忙，謝謝





2015-11-27 2:23 GMT+08:00 demo <notifications@github.com>:

**Comment by demofan** [comment]
依據設計「意外的草稿」不會阻擋發文，目前也沒有收到其他使用者的回應，剛剛有嘗試調整一版（文案也調了），請再試試看，如果還有問題的話，可能要用您實際的文章來做測試了。

**Comment by mis2000lab** [comment]
好的，謝謝您

我會試試看。  :-)

demo <notifications@github.com> 於 2015年11月27日 下午5:55 寫道：
