### ISSUE TITLE
舊會員升級的 email 如何變更？ 

### ISSUE THREAD

**Issue by jeff377** [demofan/dotblogs#27]
Dot Blog 改版要求舊會員升級要填入 email，但舊的 email 已被停用，無法收件，如何能使用新的 email 更新呢？

我的部落格如下
https://www.dotblogs.com.tw/jeff377

**Comment by demofan** [comment]
請使用網站的「聯絡我們」功能告知我們您的舊有EMAIL以及希望寄送的新EMAIL

**Comment by jeff377** [comment]
已使用「聯絡我們」回覆相關資料，再麻煩了，謝謝
