### ISSUE TITLE
文章「描述」的區塊，可以以其他顏色呈現

### ISSUE THREAD

**Issue by hatelove** [demofan/dotblogs#29]
![image](https://cloud.githubusercontent.com/assets/1528587/11416197/4a50021a-9446-11e5-96f2-8a215df4f484.png)

如上圖，紅框的部分是文章的描述/摘要，期望能以不同顏色或 css layout 來呈現，既可以類似 blog 文章常見的開頭圖片，或是整篇文章的摘要整理。

**Comment by demofan** [comment]
文章描述的初衷是讓部落客可以利用一個簡短的文字（500字）介紹文章的重點，因為這部分會直接影響到你的SEO與文章列表揭露，所以建議你想一段介紹文字，並且將希望引出的關鍵字都帶入，這樣就可以有效的提高關鍵字相關度，也是此設計的用意。
