### ISSUE TITLE
文章內容提供給 Facebook article:author 標籤的作者欄位有誤

### ISSUE THREAD

**Issue by dotjum** [demofan/dotblogs#31]
目前看到分享到 Facebook 的會呈現是 作者 Dotblogs 但文章作者應該是原作者
![image](https://cloud.githubusercontent.com/assets/5997139/11437965/7ea688e0-952c-11e5-89f0-d43122085c99.png)

檢視原始碼，可能是  article:author 沒有對應到實際作者名稱 

meta property="article:author" content="https://www.facebook.com/Dotblogs"

**Comment by demofan** [comment]
很抱歉吃了各位部落客的豆腐，因為 FB 的 author 只允許填入 fb 連結，所以之前測試的時候填入了 點部落的 fb 位置，目前已經將此設定移除。

**Comment by dotjum** [comment]
別這麼說不是吃豆腐，之前版本好像有一個標籤 (拍謝我忘了)，可以是變成那一位作者上傳並且連回去他的自己網址。


![image](https://cloud.githubusercontent.com/assets/5997139/11438524/6932f030-9530-11e5-88a8-d344fc0fb92d.png)

**Comment by demofan** [comment]
已經調整完畢
