### ISSUE TITLE
是否有管理系列文章的功能！？

### ISSUE THREAD

**Issue by kkman021** [demofan/dotblogs#32]
舊版分類改為系列文章功能，但，片尋不著管理系列文章項目的功能。

**Comment by demofan** [comment]
文章編輯內就有「系列文章」的挑選（在 Tag 上方）
如果要批次修改系列文章，可以在文章列表頁面勾選前方的 checkbox 後選擇「批次調整系列」

**Comment by demofan** [comment]
請參考 https://dotblogs.useresponse.com/knowledge-base

**Comment by kkman021** [comment]
我搞懂怎麼操作了！！原本以為跟以前一樣有個管理的介面管理選項。
原來，很直覺的用中文去管理就可以了！！
謝謝回覆！！！
