### ISSUE TITLE
Disqus的設定說明似乎與實際網站不一致

### ISSUE THREAD

**Issue by kirkchen** [demofan/dotblogs#6]
如題，
原本組態設定 => Disqus 留言板 ID => 這是什麼？
所提供的畫面似乎與Disqus目前的樣式不一致，
可能是因為Disqus改版的關係導致不同步

**Comment by demofan** [comment]
Disqus 稍早改版，我們會再製作新的說明文件

**Comment by demofan** [comment]
已經調整文案，並且製作了更詳細的說明
https://dotblogs.com.tw/dotblogs/2015/11/24/183531
