### ISSUE TITLE
win7 Ie 11登入畫面會亂掉

### ISSUE THREAD

**Issue by johnsonkao** [demofan/dotblogs#9]
![dotblog_bug](https://cloud.githubusercontent.com/assets/12950494/11331264/4de96f92-91f3-11e5-8e9b-e0660d6ba4ff.png)

win 7 ultimate 64 bit + IE11 登入畫面如附件會亂掉

**Comment by demofan** [comment]
請再次試試看

**Comment by johnsonkao** [comment]
把IE 11裡的相容性檢視設定的網站, 移除點部落, 就正常了
